### ISSUE TITLE
Release 1.0-beta5 not working.

### ISSUE THREAD

**Issue by voidtek** [djedi/DailyNotes#20]
Until yesterday, the docker image of DailyNotes stops to work.

```
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/bin/flask", line 8, in <module>
app_1  |     sys.exit(main())
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
app_1  |     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
app_1  |     return super(FlaskGroup, self).main(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
app_1  |     rv = self.invoke(ctx)
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
app_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
app_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
app_1  |     return ctx.invoke(self.callback, **ctx.params)
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
app_1  |     return callback(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
app_1  |     return f(get_current_context(), *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 425, in decorator
app_1  |     with __ctx.ensure_object(ScriptInfo).load_app().app_context():
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
app_1  |     app = locate_app(self, import_name, name)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
app_1  |     __import__(module_name)
app_1  |   File "/app/server.py", line 1, in <module>
app_1  |     from app import app
app_1  |   File "/app/app/__init__.py", line 21, in <module>
app_1  |     from app import routes, models
app_1  |   File "/app/app/routes.py", line 91, in <module>
app_1  |     def create_note():
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1315, in decorator
app_1  |     self.add_url_rule(rule, endpoint, f, **options)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
app_1  |     return f(self, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1282, in add_url_rule
app_1  |     raise AssertionError(
app_1  | AssertionError: View function mapping is overwriting an existing endpoint function: wrapper
app_1  | Traceback (most recent call last):
app_1  |   File "./verify_data_migrations.py", line 3, in <module>
app_1  |     from app import app, db
app_1  |   File "/app/app/__init__.py", line 21, in <module>
app_1  |     from app import routes, models
app_1  |   File "/app/app/routes.py", line 91, in <module>
app_1  |     def create_note():
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1315, in decorator
app_1  |     self.add_url_rule(rule, endpoint, f, **options)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
app_1  |     return f(self, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1282, in add_url_rule
app_1  |     raise AssertionError(
app_1  | AssertionError: View function mapping is overwriting an existing endpoint function: wrapper
app_1  | [2021-03-01 11:24:23 +0000] [1] [INFO] Starting gunicorn 20.0.4
app_1  | [2021-03-01 11:24:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
app_1  | [2021-03-01 11:24:23 +0000] [1] [INFO] Using worker: sync
app_1  | [2021-03-01 11:24:23 +0000] [12] [INFO] Booting worker with pid: 12
app_1  | [2021-03-01 11:24:24 +0000] [12] [ERROR] Exception in worker process
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
app_1  |     worker.init_process()
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
app_1  |     self.load_wsgi()
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
app_1  |     self.wsgi = self.app.wsgi()
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
app_1  |     self.callable = self.load()
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
app_1  |     return self.load_wsgiapp()
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
app_1  |     return util.import_app(self.app_uri)
app_1  |   File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
app_1  |     mod = importlib.import_module(module)
app_1  |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
app_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
app_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
app_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
app_1  |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
app_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1  |   File "/app/server.py", line 1, in <module>
app_1  |     from app import app
app_1  |   File "/app/app/__init__.py", line 21, in <module>
app_1  |     from app import routes, models
app_1  |   File "/app/app/routes.py", line 91, in <module>
app_1  |     def create_note():
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1315, in decorator
app_1  |     self.add_url_rule(rule, endpoint, f, **options)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 98, in wrapper_func
app_1  |     return f(self, *args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1282, in add_url_rule
app_1  |     raise AssertionError(
app_1  | AssertionError: View function mapping is overwriting an existing endpoint function: wrapper
app_1  | [2021-03-01 11:24:24 +0000] [12] [INFO] Worker exiting (pid: 12)
app_1  | [2021-03-01 11:24:24 +0000] [1] [INFO] Shutting down: Master
app_1  | [2021-03-01 11:24:24 +0000] [1] [INFO] Reason: Worker failed to boot.
```

It's not possible to use another release (all release have the same issue).

Are you working to fix this issue?

**Comment by voidtek** [comment]
I create a PR to solve the issue. https://github.com/m0ngr31/DailyNotes/pull/21
Working for me.

**Comment by m0ngr31** [comment]
That's what I get for not doing `pip freeze` on the requirements :facepalm: Thanks for the quick fix!
