### ISSUE TITLE
Can't Save with ASCII characters

### ISSUE THREAD

**Issue by TrustyTristan** [djedi/DailyNotes#4]
I noticed copying in some commands I new I would need again that it wouldn't save.
Figured out it was the Dashes rather than Hyphens that I copied

## Expected Behavior
That the file would save.

## Actual Behavior
Message: There was an error saving. Please try again.
Outcome: File doesn't save (obviously)

## Steps to Reproduce the Problem

  1. Paste in ASCII characters like –, —, “, ”
  2. Try to save

## Logs

`[2020-06-27 08:33:31,231] ERROR in app: Exception on /api/save_day [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/routes.py", line 74, in save_day
    note.text = data
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 900, in __set__
    self.fset(instance, value)
  File "/app/app/models.py", line 99, in text
    self.data = aes_encrypt(value)
  File "/app/app/models.py", line 23, in aes_encrypt
    return binascii.hexlify(cipher.encrypt(data))
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
ValueError: Input strings must be a multiple of 16 in length`

I really like it btw :)

**Comment by Janilom** [comment]
I came across this same issue over the last couple days. It looks like pasting in various characters gives the same error. I noticed it with " :  ,  -    .

**Comment by m0ngr31** [comment]
That's an interesting find. I'll look into that. Looks like it's having an issue when it goes to encrypt the data.

**Comment by burakaykan** [comment]
Faced with same error

`[2020-09-06 07:14:55,019] ERROR in app: Exception on /api/create_note [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/app/app/routes.py", line 102, in create_note
    note = Note(user_id=user.uuid, text=data)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/declarative/base.py", line 842, in _declarative_constructor
    setattr(self, k, kwargs[k])
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 900, in __set__
    self.fset(instance, value)
  File "/app/app/models.py", line 99, in text
    self.data = aes_encrypt(value)
  File "/app/app/models.py", line 23, in aes_encrypt
    return binascii.hexlify(cipher.encrypt(data))
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
ValueError: Input strings must be a multiple of 16 in length`

**Comment by m0ngr31** [comment]
Fixed with commit: https://github.com/m0ngr31/DailyNotes/commit/490e91bc9ef26512f1f6889aab3c21ad7b75bc21
